{
 "title": "Device Overview 2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Device", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  {
   "title": "System Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(time() * 1e9) - last_over_time(gnmic_boot_time_boot_time{job=\"gnmic\", source=\"$Device\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_intf_config_ip{source=\"$Device\", job=\"gnmic\", interface_name=\"Management0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_show_ver_version{source=\"$Device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_hardware_serial_no{source=\"$Device\"}",
     "legendFormat": "Serial Number"
    },
    {
     "expr": "gnmic_hardware_part_no{source=\"$Device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_hardware_firmware_version{source=\"$Device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_hardware_systemMacAddr{source=\"$Device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_mem_active{source=\"$Device\"}",
     "legendFormat": "Active Memory"
    },
    {
     "expr": "gnmic_mem_free{source=\"$Device\"}",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "gnmic_mem_buffers{source=\"$Device\"}",
     "legendFormat": "Buffers Memory"
    },
    {
     "expr": "gnmic_mem_cached{source=\"$Device\"}",
     "legendFormat": "Cached Memory"
    },
    {
     "expr": "gnmic_mem_used{source=\"$Device\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "gnmic_mem_available{job=\"gnmic\",source=\"$Device\"}",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "CPU Overview",
   "type": "stat",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_cpu_load_avg_loadAvg1m{source=\"$Device\"}",
     "legendFormat": "1-minute CPU Load Avg"
    },
    {
     "expr": "gnmic_cpu_load_avg_loadAvg5m{source=\"$Device\"}",
     "legendFormat": "5-minute CPU Load Avg"
    },
    {
     "expr": "gnmic_cpu_load_avg_loadAvg15m{source=\"$Device\"}",
     "legendFormat": "15-minute CPU Load Avg"
    }
   ]
  }
 ]
}